### ISSUE TITLE
Using bootstrap-select-country on Bootstrap 4

### ISSUE THREAD

**Issue by dandrew10** [mojoaxel/bootstrap-select-country#13] opened 2020-03-09 04:24 UTC
Hello, i've to ask something. I already used bootstrap 4 and can't downgrade it just because using this bootstrap-select-country. The dropdown is appear but can't working to display all country. Please give me a suggestion. Thank you

**Comment by mojoaxel** [comment] 2020-03-09 07:41
closing as duplicate of #1

**Closed as completed by mojoaxel** 2020-03-09 07:41 UTC
